limit: 6
max_result: 15
time_zone: "Hanoi"
max_length: 100
email: "no-reply@awesomecity.com"
discount: 10
validates:
  greater_than: 0
  name:
    maximum: 50
mailer:
  username: "apikey"
  password: "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"
  domain: "localhost"
chart:
  limit:
    month: 10
    week: 5
